//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftLibBO.ServicioWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softlib.pucp.edu.pe/", ConfigurationName="ServicioWeb.ServicioWS")]
    public interface ServicioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/buscarLibrosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/buscarLibrosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftLibBO.ServicioWeb.buscarLibrosResponse buscarLibros(SoftLibBO.ServicioWeb.buscarLibrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/buscarLibrosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/buscarLibrosResponse")]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.buscarLibrosResponse> buscarLibrosAsync(SoftLibBO.ServicioWeb.buscarLibrosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/buscarClientesRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/buscarClientesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftLibBO.ServicioWeb.buscarClientesResponse buscarClientes(SoftLibBO.ServicioWeb.buscarClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/buscarClientesRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/buscarClientesResponse")]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.buscarClientesResponse> buscarClientesAsync(SoftLibBO.ServicioWeb.buscarClientesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/buscarOtrosRecursosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/buscarOtrosRecursosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftLibBO.ServicioWeb.buscarOtrosRecursosResponse buscarOtrosRecursos(SoftLibBO.ServicioWeb.buscarOtrosRecursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/buscarOtrosRecursosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/buscarOtrosRecursosResponse")]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.buscarOtrosRecursosResponse> buscarOtrosRecursosAsync(SoftLibBO.ServicioWeb.buscarOtrosRecursosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/libro_listarTodosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/libro_listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftLibBO.ServicioWeb.libro_listarTodosResponse libro_listarTodos(SoftLibBO.ServicioWeb.libro_listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/libro_listarTodosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/libro_listarTodosResponse")]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.libro_listarTodosResponse> libro_listarTodosAsync(SoftLibBO.ServicioWeb.libro_listarTodosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/autor_listarTodosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/autor_listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftLibBO.ServicioWeb.autor_listarTodosResponse autor_listarTodos(SoftLibBO.ServicioWeb.autor_listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/autor_listarTodosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/autor_listarTodosResponse")]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.autor_listarTodosResponse> autor_listarTodosAsync(SoftLibBO.ServicioWeb.autor_listarTodosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/recurso_listarTodosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/recurso_listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftLibBO.ServicioWeb.recurso_listarTodosResponse recurso_listarTodos(SoftLibBO.ServicioWeb.recurso_listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/recurso_listarTodosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/recurso_listarTodosResponse")]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.recurso_listarTodosResponse> recurso_listarTodosAsync(SoftLibBO.ServicioWeb.recurso_listarTodosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/cliente_listarTodosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/cliente_listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftLibBO.ServicioWeb.cliente_listarTodosResponse cliente_listarTodos(SoftLibBO.ServicioWeb.cliente_listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/cliente_listarTodosRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/cliente_listarTodosResponse")]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.cliente_listarTodosResponse> cliente_listarTodosAsync(SoftLibBO.ServicioWeb.cliente_listarTodosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/cliente_obtenerPorIdRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/cliente_obtenerPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftLibBO.ServicioWeb.cliente_obtenerPorIdResponse cliente_obtenerPorId(SoftLibBO.ServicioWeb.cliente_obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softlib.pucp.edu.pe/ServicioWS/cliente_obtenerPorIdRequest", ReplyAction="http://services.softlib.pucp.edu.pe/ServicioWS/cliente_obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.cliente_obtenerPorIdResponse> cliente_obtenerPorIdAsync(SoftLibBO.ServicioWeb.cliente_obtenerPorIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public partial class libro : recurso {
        
        private autor autorField;
        
        private categoria[] categoriasField;
        
        private string editorialField;
        
        private formato formatoField;
        
        private bool formatoFieldSpecified;
        
        private string iSBNField;
        
        private string sinopsisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public autor autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("categorias", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public categoria[] categorias {
            get {
                return this.categoriasField;
            }
            set {
                this.categoriasField = value;
                this.RaisePropertyChanged("categorias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string editorial {
            get {
                return this.editorialField;
            }
            set {
                this.editorialField = value;
                this.RaisePropertyChanged("editorial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public formato formato {
            get {
                return this.formatoField;
            }
            set {
                this.formatoField = value;
                this.RaisePropertyChanged("formato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formatoSpecified {
            get {
                return this.formatoFieldSpecified;
            }
            set {
                this.formatoFieldSpecified = value;
                this.RaisePropertyChanged("formatoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
                this.RaisePropertyChanged("ISBN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sinopsis {
            get {
                return this.sinopsisField;
            }
            set {
                this.sinopsisField = value;
                this.RaisePropertyChanged("sinopsis");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public partial class autor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int idAutorField;
        
        private bool idAutorFieldSpecified;
        
        private string nacionalidadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idAutor {
            get {
                return this.idAutorField;
            }
            set {
                this.idAutorField = value;
                this.RaisePropertyChanged("idAutor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAutorSpecified {
            get {
                return this.idAutorFieldSpecified;
            }
            set {
                this.idAutorFieldSpecified = value;
                this.RaisePropertyChanged("idAutorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public partial class rol : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idRolField;
        
        private bool idRolFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idRol {
            get {
                return this.idRolField;
            }
            set {
                this.idRolField = value;
                this.RaisePropertyChanged("idRol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRolSpecified {
            get {
                return this.idRolFieldSpecified;
            }
            set {
                this.idRolFieldSpecified = value;
                this.RaisePropertyChanged("idRolSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public partial class perfil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idPerfilField;
        
        private bool idPerfilFieldSpecified;
        
        private string nombreField;
        
        private rol[] rolesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idPerfil {
            get {
                return this.idPerfilField;
            }
            set {
                this.idPerfilField = value;
                this.RaisePropertyChanged("idPerfil");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPerfilSpecified {
            get {
                return this.idPerfilFieldSpecified;
            }
            set {
                this.idPerfilFieldSpecified = value;
                this.RaisePropertyChanged("idPerfilSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("roles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public rol[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
                this.RaisePropertyChanged("roles");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private int idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private string nacionalidadField;
        
        private string nombreField;
        
        private string numeroDocumentoField;
        
        private perfil[] perfilesField;
        
        private tipoDocumento tipoDocumentoField;
        
        private bool tipoDocumentoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
                this.RaisePropertyChanged("idPersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("perfiles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public perfil[] perfiles {
            get {
                return this.perfilesField;
            }
            set {
                this.perfilesField = value;
                this.RaisePropertyChanged("perfiles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoDocumento tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoDocumentoSpecified {
            get {
                return this.tipoDocumentoFieldSpecified;
            }
            set {
                this.tipoDocumentoFieldSpecified = value;
                this.RaisePropertyChanged("tipoDocumentoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public enum tipoDocumento {
        
        /// <remarks/>
        DNI,
        
        /// <remarks/>
        RUC,
        
        /// <remarks/>
        CE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public partial class cliente : persona {
        
        private string direccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public partial class categoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private int idCategoriaField;
        
        private bool idCategoriaFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                this.idCategoriaField = value;
                this.RaisePropertyChanged("idCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idCategoriaSpecified {
            get {
                return this.idCategoriaFieldSpecified;
            }
            set {
                this.idCategoriaFieldSpecified = value;
                this.RaisePropertyChanged("idCategoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(otroRecurso))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(libro))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public partial class recurso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private double altoField;
        
        private bool altoFieldSpecified;
        
        private double anchoField;
        
        private bool anchoFieldSpecified;
        
        private bool disponibleField;
        
        private bool disponibleFieldSpecified;
        
        private System.Nullable<sbyte>[] fotoField;
        
        private int idRecursoField;
        
        private bool idRecursoFieldSpecified;
        
        private string nombreField;
        
        private double pesoField;
        
        private bool pesoFieldSpecified;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private unidadMedida unidadMedidaField;
        
        private bool unidadMedidaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double alto {
            get {
                return this.altoField;
            }
            set {
                this.altoField = value;
                this.RaisePropertyChanged("alto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool altoSpecified {
            get {
                return this.altoFieldSpecified;
            }
            set {
                this.altoFieldSpecified = value;
                this.RaisePropertyChanged("altoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
                this.RaisePropertyChanged("ancho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool anchoSpecified {
            get {
                return this.anchoFieldSpecified;
            }
            set {
                this.anchoFieldSpecified = value;
                this.RaisePropertyChanged("anchoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool disponible {
            get {
                return this.disponibleField;
            }
            set {
                this.disponibleField = value;
                this.RaisePropertyChanged("disponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disponibleSpecified {
            get {
                return this.disponibleFieldSpecified;
            }
            set {
                this.disponibleFieldSpecified = value;
                this.RaisePropertyChanged("disponibleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("foto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<sbyte>[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idRecurso {
            get {
                return this.idRecursoField;
            }
            set {
                this.idRecursoField = value;
                this.RaisePropertyChanged("idRecurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRecursoSpecified {
            get {
                return this.idRecursoFieldSpecified;
            }
            set {
                this.idRecursoFieldSpecified = value;
                this.RaisePropertyChanged("idRecursoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
                this.RaisePropertyChanged("peso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pesoSpecified {
            get {
                return this.pesoFieldSpecified;
            }
            set {
                this.pesoFieldSpecified = value;
                this.RaisePropertyChanged("pesoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
                this.RaisePropertyChanged("precioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public unidadMedida unidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("unidadMedida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unidadMedidaSpecified {
            get {
                return this.unidadMedidaFieldSpecified;
            }
            set {
                this.unidadMedidaFieldSpecified = value;
                this.RaisePropertyChanged("unidadMedidaSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public enum unidadMedida {
        
        /// <remarks/>
        UNIDAD,
        
        /// <remarks/>
        PAQUETE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public partial class otroRecurso : recurso {
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softlib.pucp.edu.pe/")]
    public enum formato {
        
        /// <remarks/>
        BOLSILLO,
        
        /// <remarks/>
        RUSTICA,
        
        /// <remarks/>
        TAPA_DURA,
        
        /// <remarks/>
        ESTUCHE,
        
        /// <remarks/>
        EBOOK,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarLibros", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarLibrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public buscarLibrosRequest() {
        }
        
        public buscarLibrosRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarLibrosResponse", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarLibrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftLibBO.ServicioWeb.libro[] @return;
        
        public buscarLibrosResponse() {
        }
        
        public buscarLibrosResponse(SoftLibBO.ServicioWeb.libro[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarClientes", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public buscarClientesRequest() {
        }
        
        public buscarClientesRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarClientesResponse", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftLibBO.ServicioWeb.cliente[] @return;
        
        public buscarClientesResponse() {
        }
        
        public buscarClientesResponse(SoftLibBO.ServicioWeb.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarOtrosRecursos", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarOtrosRecursosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public buscarOtrosRecursosRequest() {
        }
        
        public buscarOtrosRecursosRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarOtrosRecursosResponse", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarOtrosRecursosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftLibBO.ServicioWeb.otroRecurso[] @return;
        
        public buscarOtrosRecursosResponse() {
        }
        
        public buscarOtrosRecursosResponse(SoftLibBO.ServicioWeb.otroRecurso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="libro_listarTodos", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class libro_listarTodosRequest {
        
        public libro_listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="libro_listarTodosResponse", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class libro_listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftLibBO.ServicioWeb.libro[] @return;
        
        public libro_listarTodosResponse() {
        }
        
        public libro_listarTodosResponse(SoftLibBO.ServicioWeb.libro[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autor_listarTodos", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class autor_listarTodosRequest {
        
        public autor_listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autor_listarTodosResponse", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class autor_listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftLibBO.ServicioWeb.autor[] @return;
        
        public autor_listarTodosResponse() {
        }
        
        public autor_listarTodosResponse(SoftLibBO.ServicioWeb.autor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recurso_listarTodos", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class recurso_listarTodosRequest {
        
        public recurso_listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recurso_listarTodosResponse", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class recurso_listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftLibBO.ServicioWeb.recurso[] @return;
        
        public recurso_listarTodosResponse() {
        }
        
        public recurso_listarTodosResponse(SoftLibBO.ServicioWeb.recurso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_listarTodos", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_listarTodosRequest {
        
        public cliente_listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_listarTodosResponse", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftLibBO.ServicioWeb.cliente[] @return;
        
        public cliente_listarTodosResponse() {
        }
        
        public cliente_listarTodosResponse(SoftLibBO.ServicioWeb.cliente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_obtenerPorId", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idCliente;
        
        public cliente_obtenerPorIdRequest() {
        }
        
        public cliente_obtenerPorIdRequest(int idCliente) {
            this.idCliente = idCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cliente_obtenerPorIdResponse", WrapperNamespace="http://services.softlib.pucp.edu.pe/", IsWrapped=true)]
    public partial class cliente_obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softlib.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftLibBO.ServicioWeb.cliente @return;
        
        public cliente_obtenerPorIdResponse() {
        }
        
        public cliente_obtenerPorIdResponse(SoftLibBO.ServicioWeb.cliente @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWSChannel : SoftLibBO.ServicioWeb.ServicioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWSClient : System.ServiceModel.ClientBase<SoftLibBO.ServicioWeb.ServicioWS>, SoftLibBO.ServicioWeb.ServicioWS {
        
        public ServicioWSClient() {
        }
        
        public ServicioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftLibBO.ServicioWeb.buscarLibrosResponse SoftLibBO.ServicioWeb.ServicioWS.buscarLibros(SoftLibBO.ServicioWeb.buscarLibrosRequest request) {
            return base.Channel.buscarLibros(request);
        }
        
        public SoftLibBO.ServicioWeb.libro[] buscarLibros(string nombre) {
            SoftLibBO.ServicioWeb.buscarLibrosRequest inValue = new SoftLibBO.ServicioWeb.buscarLibrosRequest();
            inValue.nombre = nombre;
            SoftLibBO.ServicioWeb.buscarLibrosResponse retVal = ((SoftLibBO.ServicioWeb.ServicioWS)(this)).buscarLibros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.buscarLibrosResponse> SoftLibBO.ServicioWeb.ServicioWS.buscarLibrosAsync(SoftLibBO.ServicioWeb.buscarLibrosRequest request) {
            return base.Channel.buscarLibrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.buscarLibrosResponse> buscarLibrosAsync(string nombre) {
            SoftLibBO.ServicioWeb.buscarLibrosRequest inValue = new SoftLibBO.ServicioWeb.buscarLibrosRequest();
            inValue.nombre = nombre;
            return ((SoftLibBO.ServicioWeb.ServicioWS)(this)).buscarLibrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftLibBO.ServicioWeb.buscarClientesResponse SoftLibBO.ServicioWeb.ServicioWS.buscarClientes(SoftLibBO.ServicioWeb.buscarClientesRequest request) {
            return base.Channel.buscarClientes(request);
        }
        
        public SoftLibBO.ServicioWeb.cliente[] buscarClientes(string nombre) {
            SoftLibBO.ServicioWeb.buscarClientesRequest inValue = new SoftLibBO.ServicioWeb.buscarClientesRequest();
            inValue.nombre = nombre;
            SoftLibBO.ServicioWeb.buscarClientesResponse retVal = ((SoftLibBO.ServicioWeb.ServicioWS)(this)).buscarClientes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.buscarClientesResponse> SoftLibBO.ServicioWeb.ServicioWS.buscarClientesAsync(SoftLibBO.ServicioWeb.buscarClientesRequest request) {
            return base.Channel.buscarClientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.buscarClientesResponse> buscarClientesAsync(string nombre) {
            SoftLibBO.ServicioWeb.buscarClientesRequest inValue = new SoftLibBO.ServicioWeb.buscarClientesRequest();
            inValue.nombre = nombre;
            return ((SoftLibBO.ServicioWeb.ServicioWS)(this)).buscarClientesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftLibBO.ServicioWeb.buscarOtrosRecursosResponse SoftLibBO.ServicioWeb.ServicioWS.buscarOtrosRecursos(SoftLibBO.ServicioWeb.buscarOtrosRecursosRequest request) {
            return base.Channel.buscarOtrosRecursos(request);
        }
        
        public SoftLibBO.ServicioWeb.otroRecurso[] buscarOtrosRecursos(string nombre) {
            SoftLibBO.ServicioWeb.buscarOtrosRecursosRequest inValue = new SoftLibBO.ServicioWeb.buscarOtrosRecursosRequest();
            inValue.nombre = nombre;
            SoftLibBO.ServicioWeb.buscarOtrosRecursosResponse retVal = ((SoftLibBO.ServicioWeb.ServicioWS)(this)).buscarOtrosRecursos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.buscarOtrosRecursosResponse> SoftLibBO.ServicioWeb.ServicioWS.buscarOtrosRecursosAsync(SoftLibBO.ServicioWeb.buscarOtrosRecursosRequest request) {
            return base.Channel.buscarOtrosRecursosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.buscarOtrosRecursosResponse> buscarOtrosRecursosAsync(string nombre) {
            SoftLibBO.ServicioWeb.buscarOtrosRecursosRequest inValue = new SoftLibBO.ServicioWeb.buscarOtrosRecursosRequest();
            inValue.nombre = nombre;
            return ((SoftLibBO.ServicioWeb.ServicioWS)(this)).buscarOtrosRecursosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftLibBO.ServicioWeb.libro_listarTodosResponse SoftLibBO.ServicioWeb.ServicioWS.libro_listarTodos(SoftLibBO.ServicioWeb.libro_listarTodosRequest request) {
            return base.Channel.libro_listarTodos(request);
        }
        
        public SoftLibBO.ServicioWeb.libro[] libro_listarTodos() {
            SoftLibBO.ServicioWeb.libro_listarTodosRequest inValue = new SoftLibBO.ServicioWeb.libro_listarTodosRequest();
            SoftLibBO.ServicioWeb.libro_listarTodosResponse retVal = ((SoftLibBO.ServicioWeb.ServicioWS)(this)).libro_listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.libro_listarTodosResponse> SoftLibBO.ServicioWeb.ServicioWS.libro_listarTodosAsync(SoftLibBO.ServicioWeb.libro_listarTodosRequest request) {
            return base.Channel.libro_listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.libro_listarTodosResponse> libro_listarTodosAsync() {
            SoftLibBO.ServicioWeb.libro_listarTodosRequest inValue = new SoftLibBO.ServicioWeb.libro_listarTodosRequest();
            return ((SoftLibBO.ServicioWeb.ServicioWS)(this)).libro_listarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftLibBO.ServicioWeb.autor_listarTodosResponse SoftLibBO.ServicioWeb.ServicioWS.autor_listarTodos(SoftLibBO.ServicioWeb.autor_listarTodosRequest request) {
            return base.Channel.autor_listarTodos(request);
        }
        
        public SoftLibBO.ServicioWeb.autor[] autor_listarTodos() {
            SoftLibBO.ServicioWeb.autor_listarTodosRequest inValue = new SoftLibBO.ServicioWeb.autor_listarTodosRequest();
            SoftLibBO.ServicioWeb.autor_listarTodosResponse retVal = ((SoftLibBO.ServicioWeb.ServicioWS)(this)).autor_listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.autor_listarTodosResponse> SoftLibBO.ServicioWeb.ServicioWS.autor_listarTodosAsync(SoftLibBO.ServicioWeb.autor_listarTodosRequest request) {
            return base.Channel.autor_listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.autor_listarTodosResponse> autor_listarTodosAsync() {
            SoftLibBO.ServicioWeb.autor_listarTodosRequest inValue = new SoftLibBO.ServicioWeb.autor_listarTodosRequest();
            return ((SoftLibBO.ServicioWeb.ServicioWS)(this)).autor_listarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftLibBO.ServicioWeb.recurso_listarTodosResponse SoftLibBO.ServicioWeb.ServicioWS.recurso_listarTodos(SoftLibBO.ServicioWeb.recurso_listarTodosRequest request) {
            return base.Channel.recurso_listarTodos(request);
        }
        
        public SoftLibBO.ServicioWeb.recurso[] recurso_listarTodos() {
            SoftLibBO.ServicioWeb.recurso_listarTodosRequest inValue = new SoftLibBO.ServicioWeb.recurso_listarTodosRequest();
            SoftLibBO.ServicioWeb.recurso_listarTodosResponse retVal = ((SoftLibBO.ServicioWeb.ServicioWS)(this)).recurso_listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.recurso_listarTodosResponse> SoftLibBO.ServicioWeb.ServicioWS.recurso_listarTodosAsync(SoftLibBO.ServicioWeb.recurso_listarTodosRequest request) {
            return base.Channel.recurso_listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.recurso_listarTodosResponse> recurso_listarTodosAsync() {
            SoftLibBO.ServicioWeb.recurso_listarTodosRequest inValue = new SoftLibBO.ServicioWeb.recurso_listarTodosRequest();
            return ((SoftLibBO.ServicioWeb.ServicioWS)(this)).recurso_listarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftLibBO.ServicioWeb.cliente_listarTodosResponse SoftLibBO.ServicioWeb.ServicioWS.cliente_listarTodos(SoftLibBO.ServicioWeb.cliente_listarTodosRequest request) {
            return base.Channel.cliente_listarTodos(request);
        }
        
        public SoftLibBO.ServicioWeb.cliente[] cliente_listarTodos() {
            SoftLibBO.ServicioWeb.cliente_listarTodosRequest inValue = new SoftLibBO.ServicioWeb.cliente_listarTodosRequest();
            SoftLibBO.ServicioWeb.cliente_listarTodosResponse retVal = ((SoftLibBO.ServicioWeb.ServicioWS)(this)).cliente_listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.cliente_listarTodosResponse> SoftLibBO.ServicioWeb.ServicioWS.cliente_listarTodosAsync(SoftLibBO.ServicioWeb.cliente_listarTodosRequest request) {
            return base.Channel.cliente_listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.cliente_listarTodosResponse> cliente_listarTodosAsync() {
            SoftLibBO.ServicioWeb.cliente_listarTodosRequest inValue = new SoftLibBO.ServicioWeb.cliente_listarTodosRequest();
            return ((SoftLibBO.ServicioWeb.ServicioWS)(this)).cliente_listarTodosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftLibBO.ServicioWeb.cliente_obtenerPorIdResponse SoftLibBO.ServicioWeb.ServicioWS.cliente_obtenerPorId(SoftLibBO.ServicioWeb.cliente_obtenerPorIdRequest request) {
            return base.Channel.cliente_obtenerPorId(request);
        }
        
        public SoftLibBO.ServicioWeb.cliente cliente_obtenerPorId(int idCliente) {
            SoftLibBO.ServicioWeb.cliente_obtenerPorIdRequest inValue = new SoftLibBO.ServicioWeb.cliente_obtenerPorIdRequest();
            inValue.idCliente = idCliente;
            SoftLibBO.ServicioWeb.cliente_obtenerPorIdResponse retVal = ((SoftLibBO.ServicioWeb.ServicioWS)(this)).cliente_obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.cliente_obtenerPorIdResponse> SoftLibBO.ServicioWeb.ServicioWS.cliente_obtenerPorIdAsync(SoftLibBO.ServicioWeb.cliente_obtenerPorIdRequest request) {
            return base.Channel.cliente_obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftLibBO.ServicioWeb.cliente_obtenerPorIdResponse> cliente_obtenerPorIdAsync(int idCliente) {
            SoftLibBO.ServicioWeb.cliente_obtenerPorIdRequest inValue = new SoftLibBO.ServicioWeb.cliente_obtenerPorIdRequest();
            inValue.idCliente = idCliente;
            return ((SoftLibBO.ServicioWeb.ServicioWS)(this)).cliente_obtenerPorIdAsync(inValue);
        }
    }
}
